### PR TITLE
feat: Add support for externally managed SSO users (ie. SCIM)

### PR DESCRIPTION
**Pull request by fcuello-fudo**
Allow defining users as "external" when they are created by an external provider like SCIM but we still want to manage groups and groups assignements here.

### CODE REVIEW

**Comment by novekm** [comment]
Hi @fcuello-fudo, this is the current functionality of the module.

When users are created externally (in external Identity Provider such as Okta, Azure AD, etc.), these are synced via SCIM to IAM Identity Center once configured. The `aws_identitystore_user` resource is only used to create users (e.g. if you want to use IAM Identity Center as the identity provider, not an external IdP). The same applies to groups that you wish to create (`aws_identity_store_group`). These would not be created via Terraform if you are syncing with SCIM. 

The module currently supports being able to assign permissions to the users/groups via the data sources (which would fetch the users/groups after synced from external IDP)

**Comment by novekm** [comment]
> When using Google Workspace, the groups are not created using SCIM but the users are, this leaves the groups managed by terraform and the users by SCIM.

Ah, I forgot about that limitation Google Workspace has with SCIM. Have you looked into [ssosync](https://github.com/awslabs/ssosync) as a method to sync the groups as well as the users from Google Workspace?

**Comment by novekm** [comment]
I think I get what you may be looking for. For a sample tf config, are you looking for something like the following? 
```hcl
module "aws-iam-identity-center" {
  source = "aws-ia/iam-identity-center/aws" 

  // Create desired GROUPS in IAM Identity Center (since Google Workspace SCIM will not sync groups)
  sso_groups = {
    Admin : {
      group_name        = "Admin"
      group_description = "Admin IAM Identity Center Group"
    },
    Dev : {
      group_name        = "Dev"
      group_description = "Dev IAM Identity Center Group"
    },
    # etc.
  }

  // Reference EXISTING users to assign them to groups in IAM IdC (users synced from Google Workspace)
  google_sso_users = {
    GoogleUser1 : {
      group_membership = ["Admin", "Dev", "QA", "Audit"]
      user_name        = "google1"
      given_name       = "Google"
      family_name      = "User 1"
      email            = "nuzumaki@hiddenleaf.village"
    },
    GoogleUser2 : {
      group_membership = ["QA", "Audit"]
      user_name        = "google2"
      given_name       = "Google"
      family_name      = "User2"
      email            = "suchiha@hiddenleaf.village"
    },
    # etc.
  }

  # permission sets
  
  # account assignments
  

}

```

**Comment by smellyspice** [comment]
@novekm - with regards to your [ask](https://github.com/aws-ia/terraform-aws-iam-identity-center/issues/33#issuecomment-2134053181) for me to look at the comment in this PR -- I think the big miss here is that the native Terraform provider doesn't provide for a [list-users](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/identitystore/list-users.html) operation. Being able to list all your SCIM users into a data resource would make life much easier. 

I've done this using a terraform [external provider](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/external) that then calls the AWS CLI command. I then use a second external provider to call the [AWS SCIM API](https://docs.aws.amazon.com/singlesignon/latest/developerguide/getuser.html) `GetUser` operation to enrich the user data. 

This is still a work in progress, but I'm hoping I can get enough enriched data from SCIM so as to place SCIM users into some default, group based, permission sets. For example, I auto-generate groups based on some `Department` information fetch through SCIM and then I populate my discovered users into those groups. This gives us a good starting point for basic access. I then hand create custom groups, adding discovered users (like @fcuello-fudo has in his comment) and then merge the two groups into one larger `sso_groups` var that I then pass to this module. 

But now I see in-line policies aren't supported yet. So more modifications are needed. I've done so much hacking to this module at this point that it probably makes more sense to just merge all the work and use the native resources directly.

**Comment by novekm** [comment]
Hi @fcuello-fudo - I like the approach, my only concern is that it could lead to duplication of code when trying to add users to multiple groups (e.g. for 10 groups, `user1@example.com` would need to be pasted 10 times, increasing the amount of code). This could also make readability a bit hard as the number of users within each group increases. I'd also like to try to avoid making major changes to the module if at all possible. 

We're currently working to review PR #20 and may add this additional Google Workspace functionality in the next release, or soon after. We'd likely want to keep the versions a bit more distinct (e.g. `v0.0.3` - add inline policies, permissions boundaries, and update use of data sources and `v0.0.4` - add support for managing groups only (and users from external IdP) for the Google Workspace use case.

@smellyspice yes we're aware of this unfortunate limitation of the current version of the Terraform AWS provider - you can [list groups](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/identitystore_groups), but currently can only list individual users and must loop through to fetch all of them. I agree that a data source for this would make things a lot easier. Separately, I'm working on a PR for the AWS provider to add this support, but don't have a current timeline on when I'll have the time to finish that up. I'll continue to reply here as updates are made. 

We're targeting to have #20 merged in and new release cut hopefully within the next 1-2 weeks, and a following PR adding the other support mentioned (specifically to address the nuances of Google Workspace) hopefully soon thereafter.

**Comment by novekm** [comment]
Hi @fcuello-fudo, this functionality has been added in `v0.0.5` which was released today 🙂

**Pull request closed without merging**
