### PR TITLE
add output for sso groups ids

### PR DESCRIPTION
**Pull request by matiasbertani**
To be able to reference them outside the module.

### CODE REVIEW

**Comment by matiasbertani** [comment]
@novekm / @tbulding Could you give this a look. I think It is a very useful feature

**Comment by novekm** [comment]
Hi @matiasbertani, thanks for your contribution! PR looks good and end-to-end test completed successfully. Can you please update the VERSION file in your PR to be `v0.0.2`? then I will approve/merge

**Comment by matiasbertani** [comment]
> Can you please update the VERSION file in your PR to be v0.0.2?

@novekm Done!

**Review by novekm — APPROVED** [review]
LGTM 🚀

**Pull request merged**
